# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: QUOC THINH DANG
title: ReactJS Developer
email: eeit104@gmail.com
phone: (+84) 903623296

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username:
github_username:  nanxy-tran
# stackoverflow_username:
# dribbble_username:
facebook_username: ahxtpn
# flickr_username:
#instagram_username:
linkedin_username: quoc-thinh-dang-38319a195
# xing_username:
# pinterest_username:
# youtube_username: user=dw1YeQl_592n78flMMvdNQ
# googleplus_username:
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

about_title: About me 😎
#about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  It's nice to meet you, I'm Thinh, a self-taught developer, used to be a police officer but then drop out when I realized that programming is the most suitable career.
  I worked with mobile stuffs and web, but able to find and join new area. Enjoy coding and coffee, but not threshold or release.
  Currently I'm learning more about Javascript frameworks in depth and most skilled in ReactJS

content:
  - title: ReactJS/Native developer # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: My stack
        link: github.com/Nanxy-Tran
        # link_text: Project Website
        additional_links:
          - title:  Nanxy-Tran
            icon: fab fa-github
          #   icon: fab fa-github
        description: |  # this will include new lines to allow paragraphs
          - <b>Language</b>: <mark>Javascript</mark>, <mark>Typescript</mark>, <mark>Python</mark>
          - <b>Library</b>: <mark>ReactJS</mark> <mark>VueJS</mark> <mark>Tailwindcss</mark>
          - <b>Framework</b>: <mark>React Native</mark> <mark>NextJS</mark>
          - <b>Other</b>: <mark>Rest</mark> <mark>Appcenter</mark> <mark>GithubActions</mark> <mark>Prisma</mark> <mark>SQL</mark>
          - <b>Style</b>: *prefer* <mark>Clean code</mark>, <mark>Functional programming</mark>, <mark>Webstorm</mark> and <mark>Automation</mark>.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: |
          Aspire Financial Technologies Pte. Ltd.
          <p><i>All-in-one finance OS in Southeast Asia</i><p>
        link: aspireapp.com
        sub_title: Mobile developer
        caption: March 2020 - Present
        description: | # this will include new lines to allow paragraphs
          The product of banking, provide money service to SMEs by connecting the dots
            - Maintain and implements features of transfer/receive money, and its eco-services
            - Devops stuffs for easier <mark>Github</mark> experience
            - Working with RESTful API
            - Refactoring and review code
            - Tech stack: <mark>React Native</mark> , <mark>Laravel</mark> , <mark>Appcenter</mark> , <mark>VueJS</mark>
            - Team scale: ~10 people

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: People’s Security University
        caption: 2014 - 2018
        sub_title: BSc of Law
        description: | # this will include new lines to allow paragraphs
          I had been learning 4 years at this school to be an officer. Although, I realized this was not my suitable career,
          I never reget about this decision. After all, university is a place teach you to learn, shape your characteristics in order
          to deal with world of rapid change out there.

      - layout: left
        title: Self-taught
        caption: 2019 - Present
        description: | # this will include new lines to allow paragraphs
          Struggling at first is envitable when I meet programming. There were hundles of terminologies that I did not even know what they are.
          But reading and trying taught me a lots, and I grapsed the main idea of how computer works. After given an opportunity to join a fintech startup
          I learnt many things and gradually acknowledged of what I have read before.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - I enjoy learning both tech and non-tech stuffs to find the balance point of life. Working and enjoy should come together.
      You can visit my <mark>Blog</mark> [here](https://beslow.vercel.app){:target="_blank" rel="noopener"}, I created it to share my thought and my experience.
      - My #2 hobby is aquascape 🐠 and shrimp keeping 🦐

# Footer
footer_show_references: true
references_title: You can print this page as PDF by right-click and print

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
]